### ISSUE TITLE
I'm getting this error.How to solve this?

### ISSUE THREAD

**Issue by saisuhas** [mahaveerverma/hand-gesture-recognition-opencv#8]
Traceback (most recent call last):
  File "C:\Users\Suhas\Desktop\Mahaveer Varma hand-gesture-recognition-opencv-master\HandRecognition.py", line 190, in <module>
    fg_frame=remove_bg(frame)
  File "C:\Users\Suhas\Desktop\Mahaveer Varma hand-gesture-recognition-opencv-master\HandRecognition.py", line 166, in remove_bg
    fg_mask=bg_model.apply(frame)
TypeError: Incorrect type of self (must be 'BackgroundSubtractorMOG2' or its derivative)

**Comment by beingabstrac** [comment]
Replace 'BackgroundSubtractorMOG2' with 'createBackgroundSubtractorMOG2'.
That worked for me.

**Comment by saisuhas** [comment]
Thank you so much!This one worked for me

**Comment by mahaveerverma** [comment]
Thanks @rishirD for solving this one :)
